services:
  db:
    image: 'postgres'
    environment:
      POSTGRES_USER: mathesu
      POSTGRES_DB: crypto
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/data/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
